FROM node:20-alpine

RUN apk add --no-cache libc6-compat python3 make g++ openssl

WORKDIR /app

COPY package.json package-lock.json* ./
COPY prisma ./prisma/

RUN npm install

RUN npx prisma generate

EXPOSE 3000
