FROM node:20-slim

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY socket-server/package.json socket-server/package-lock.json* ./
COPY prisma ./prisma/

RUN npm install

RUN npx prisma generate

EXPOSE 4000
